name: myenv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2024.7.2
  - filelock=3.13.1
  - freetype=2.12.1
  - fsspec=2024.3.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.4.0
  - openssl=3.0.14
  - pillow=10.4.0
  - pip=24.0
  - python=3.8.19
  - pytorch-cpu=2.3.0
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.11.0
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - gunicorn==20.1.0
      - blinker==1.8.2
      - click==8.1.7
      - flask==3.0.3
      - flask-cors==4.0.1
      - importlib-metadata==8.2.0
      - itsdangerous==2.2.0
      - torch==2.3.1
      - torchaudio==2.3.1
      - torchvision==0.18.1
      - werkzeug==3.0.3
      - zipp==3.19.2
